# Generated by Django 2.0.4 on 2018-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
