# Generated by Django 2.0.4 on 2018-04-19 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_film_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
