# Generated by Django 2.0.4 on 2018-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20180419_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['added']},
        ),
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
